spring:
  profiles:
    active: dev

---
# Coloque aqui suas configurações de Desenvolvimento
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    platform: org.hibernate.dialect.H2Dialect
    driver-class-name: org.h2.Driver
  config:
    activate:
      on-profile: dev