DROP TABLE IF EXISTS ALUGUEIS;
DROP TABLE IF EXISTS CLIENTES;
DROP TABLE IF EXISTS IMOVEIS;
DROP TABLE IF EXISTS LOCACAO;


CREATE TABLE CLIENTES
(
    ID            INT AUTO_INCREMENT PRIMARY KEY,
    NOME_CLIENTE  VARCHAR(45) NOT NULL,
    CPF           NUMERIC(15) NOT NULL,
    TELEFONE1     NUMERIC(15) NOT NULL,
    TELEFONE2     NUMERIC(15),
    EMAIL         VARCHAR(50) DEFAULT NULL,
    DT_NASCIMENTO DATE
);

CREATE TABLE IMOVEIS
(
    ID                     INT AUTO_INCREMENT PRIMARY KEY,
    TIPO_IMOVEL            VARCHAR(100) NOT NULL,
    ENDERECO               TEXT,
    BAIRRO                 VARCHAR(45),
    CEP                    NUMERIC(8),
    METRAGEM               NUMERIC(10, 2),
    DORMITORIOS            TINYINT,
    BANHEIROS              TINYINT,
    SUITES                 TINYINT,
    VAGAS_GARAGEM          TINYINT,
    VALOR_ALUGUEL_SUGERIDO NUMERIC(10, 2),
    OBS                    TEXT
);
CREATE TABLE LOCACAO
(
    ID_LOCACAO       INT AUTO_INCREMENT PRIMARY KEY,
    ID_IMOVEL        INT,
    ID_INQUILINO     INT,
    VALOR_ALUGUEL    NUMERIC(10, 2),
    PERCENTUAL_MULTA NUMERIC(5, 2),
    DIA_VENCIMENTO   TINYINT,
    DATA_INICIO      DATE,
    DATA_FIM         DATE,
    ATIVO            BOOLEAN,
    OBS              TEXT,
    CONSTRAINT ImovelID FOREIGN KEY (ID_IMOVEL) REFERENCES IMOVEIS (ID),
    CONSTRAINT InquilinoID FOREIGN KEY (ID_INQUILINO) REFERENCES CLIENTES (ID)
);

CREATE TABLE ALUGUEIS
(
    ID_LOCACAO      INT,
    CONSTRAINT LocacaoID FOREIGN KEY (ID_LOCACAO) REFERENCES LOCACAO (ID_LOCACAO),
    DATA_VENCIMENTO DATE,
    VALOR_PAGO      NUMERIC(10, 2),
    DATA_PAGAMENTO  DATE,
    OBS             TEXT
);